import Head from "next/head";
import { BattleShip } from "@/features/battle-naval/components/battle-ship";

export default function Home() {

  return (
    <>
      <Head>
        <title>Battleship Demo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BattleShip/>
      {/* <Initialize/> */}
    </>
  );
}
